FROM fedora:42

# Install system dependencies
RUN dnf -y install \
    centpkg \
    curl \
    glab \
    git \
    python3 \
    python3-pip \
    python3-redis \
    rpmlint \
    rpmdevtools \
    rpmbuild \
    spectool \
    && dnf -y clean all

COPY beeai-gemini.patch /tmp

# Install BeeAI Framework and Phoenix
RUN pip3 install \
    beeai-framework[mcp,duckduckgo] \
    openinference-instrumentation-beeai \
    arize-phoenix-otel \
    && cd /usr/local/lib/python3.13/site-packages \
    && patch -p2 -i /tmp/beeai-gemini.patch

# Create user
RUN useradd -m -G wheel beeai

# Create directories
# `/home/beeai/agents/` should be directly copied for Openshift deployment
# although it is locally mounted through a volume
COPY agents/ /home/beeai/agents/
RUN chgrp -R root /home/beeai && chmod -R g+rwX /home/beeai

USER beeai
WORKDIR /home/beeai

CMD ["/bin/bash"]
